// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-fx4_QMHHJIjvtFSILtgIvv-aSVxoEw',
    appId: '1:172268892799:web:1b2b654fc05f42296d054a',
    messagingSenderId: '172268892799',
    projectId: 'agora-ee1b3',
    authDomain: 'agora-ee1b3.firebaseapp.com',
    storageBucket: 'agora-ee1b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoqAfv6Za74mcOmvP-JA89dJnr87kVf8',
    appId: '1:172268892799:android:59ad95289ce638906d054a',
    messagingSenderId: '172268892799',
    projectId: 'agora-ee1b3',
    storageBucket: 'agora-ee1b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbSFJWsA5hCtDqfxdNUnEonqmj1Vdfbo',
    appId: '1:172268892799:ios:c7549e21a57086de6d054a',
    messagingSenderId: '172268892799',
    projectId: 'agora-ee1b3',
    storageBucket: 'agora-ee1b3.appspot.com',
    iosClientId: '172268892799-vetgkplk989dj73bcmot9j221fm0ej6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAgora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbSFJWsA5hCtDqfxdNUnEonqmj1Vdfbo',
    appId: '1:172268892799:ios:c7549e21a57086de6d054a',
    messagingSenderId: '172268892799',
    projectId: 'agora-ee1b3',
    storageBucket: 'agora-ee1b3.appspot.com',
    iosClientId: '172268892799-vetgkplk989dj73bcmot9j221fm0ej6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAgora',
  );
}
